### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Kif11** [paulwinex/houdini_install_script#1]
Getting this error on Windows machine

```
C:\Users\ee\Desktop>python houdini_install.py -u ***** -p ***** -i "C:\Program Files\houdini"
Login on https://www.sidefx.com/login/ ...
Get last build version...
Traceback (most recent call last):
  File "houdini_install.py", line 93, in <module>
    a = s.find('div', {'class': lambda x: x and 'category-'+category in x.split()}).find('a')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by paulwinex** [comment]
Maybe login is failed?

**Comment by dani3315** [comment]
I get the same error trying to install on a Linux EC2 Instance:

Login on https://www.sidefx.com/login/ ...
Get last build version...
Traceback (most recent call last):
  File "./houdini_install.py", line 119, in <module>
    a = s.find('div', {'class': lambda x: x and 'category-'+category in x.split()}).find('a')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by paulwinex** [comment]
Something changed on builds page. I need to fix parsing code. Maybe i can do it soon.
You can do in itself if you can)

**Comment by dani3315** [comment]
Thank you very much. That would be great!!!

**Comment by JoaoChaves96** [comment]
Was anyone able to solve this error?

**Comment by paulwinex** [comment]
Hi, i am was fix it! But i have not any pc for testing(
Please try new script and report me.
Get the code from the new branch [new-build-list-request](https://github.com/paulwinex/houdini_install_script/tree/new-build-list-request)

**Comment by JoaoChaves96** [comment]
Hey @paulwinex ! The script gives a syntax error: 


file "./houdini_install.py", line 110
    build_name = f"{build['version']}.{build['build']}"
                                                                                    ^
SyntaxError: invalid syntax

**Comment by paulwinex** [comment]
> SyntaxError: invalid syntax

Oh, i remake it with Python3. Check the new commit, im fixed this line for python2 compatible

**Comment by JoaoChaves96** [comment]
Hey, so I tried the script again and i only had to make some small fixes: 

OS = dict(win32='win', linux='linux', darwin='mac')[sys.platform] --> line 90

the key 'linux' should be 'linux2' instead.

Also, on line 68, you have: 

return '/'.join([install_dir.rstrip('/'), build]), and it should be:

return '/'.join([install_dir.rstrip('/'), build['build']]).

After that I was able to run the script . Nevertheless, the whole point of this was to be able to import the hou module inside a python shell. After installing houdini I'm yet not able to import the module. Do you know if I need additional configuration? I'm trying to run this inside a docker container with Ubuntu 18.04

**Comment by paulwinex** [comment]
@JoaoChaves96 thanks for testing. This is my output on Ubuntu 18:

```python
>>> import platform, sys
>>> platform.platform()
'Linux-4.15.0-29-generic-x86_64-with-Ubuntu-18.04-bionic'
>>> sys.platform
'linux'
```
Where you get 'linux2'?

**Comment by paulwinex** [comment]
@JoaoChaves96 
To import `hou` in you script you must start separate process with `hython` executable. 
Also you can start `houdini_install.py` with `hython` from previous installed Houdini.

But I think we need to upgrade my script and replace inline code to functions and add `if __name__ == '__main__'` block.
When i add it you can start system python, import install script and call function which will return install path. In next step you can start subprocess with `hython`. Example:

```bahs
# bash
$ python my_hou_installer.py
```
```python
# python
import os, subprocess
import houdini_install
install_path = houdini_install.install()
hython = os.path.join(install_path, 'bin', 'hython')
subprocess.call([hython, 'my_conf_script.py', '--path', install_path])
```
Probably you need to cleanup env before this call.

**Comment by paulwinex** [comment]
So, i was add `linux` and `linux2` to list and fix folder creation. You can check now.

**Comment by JoaoChaves96** [comment]
Another thing I noticed, when setting the flags to install:

flags = '--auto-install --accept-EULA --make-dir',

you actually need to input the data you want, like this:

flags = '--auto-install --accept-EULA 2020-05-05 --make-dir'

**Comment by paulwinex** [comment]
@JoaoChaves96 Actually if you need full functionality probably you need to use official api
[https://www.sidefx.com/docs/api/download/index.html#api-methods](https://www.sidefx.com/docs/api/download/index.html#api-methodsl)

**Comment by JoaoChaves96** [comment]
Hm I see.

When I try to execute hython, I get this error: 

No licenses could be found to run this application.
	Please check for a valid license server host

Do you happen to know how can I set this up?

**Comment by paulwinex** [comment]
You need to correctly setup license server. Check documentation.
[https://www.sidefx.com/faq/license-management/](https://www.sidefx.com/faq/license-management/)
[https://www.sidefx.com/faq/question/492/](https://www.sidefx.com/faq/question/492/)
If you lic server is ok i dont know how to help you( Probably you need to configure  License Administrator

**Comment by JoaoChaves96** [comment]
so, I needed to get a non-comercial license from here

https://www.sidefx.com/services/non-commercial-license/

After setting that up, I managed to run hython and import hou 

Thanks for the help!
